### ISSUE TITLE
Design ERD

### ISSUE THREAD

**Issue by lidathy-real** [PNC-WEP-ONE-WEEK-PROJECT/PHP-DB-G22#2]
#2

**Comment by sophyseuy** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/92014931/158589642-6fc15dfa-693b-41dc-9e77-e8b7442df941.png">

**Comment by ronanpnc** [comment]
MIssing types

and  primary and forreign key


and maybe some attributes
